
export const tree = {
  children: [{
    children: [
      {
        children: [
          {
            children: [],
            count: 1,
            depth: 0,
            error: "",
            expanded: false,
            fileName: "GrandBaby One-A",
            filePath:
              "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/components/Sidebar.tsx",
            id: "FA6sF8JbqMloijRT6QOxHh3i5p1v29bJ",
            importPath: "/",
            name: "GrandBaby One-A",
            parentList: [
              "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/index.tsx",
            ],
            props: {
              oneWay: [],
              twoWay: [],
            },
            reactRouter: false,
            reduxConnect: false,
            thirdParty: false,
            // [[Prototype]]: Object,
          },
          {
            children: [
              {
                children: [],
                count: 1,
                depth: 0,
                error: "",
                expanded: false,
                fileName: "G-G-Baby 1",
                filePath:
                  "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/components/Sidebar.tsx",
                id: "FA6sF8JbqMloijRT6QOxHh3i5p1v29bJ",
                importPath: "/",
                name: "G-G-Baby 1",
                parentList: [
                  "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/index.tsx",
                ],
                props: {
                  oneWay: ['p-3'],
                  twoWay: [],
                },
                reactRouter: false,
                reduxConnect: false,
                thirdParty: false,
                // [[Prototype]]: Object,
              },
            ],
            count: 1,
            depth: 0,
            error: "",
            expanded: false,
            fileName: "GrandBaby One-B",
            filePath:
              "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/components/Sidebar.tsx",
            id: "FA6sF8JbqMloijRT6QOxHh3i5p1v29bJ",
            importPath: "/",
            name: "GrandBaby One-B",
            parentList: [
              "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/index.tsx",
            ],
            props: {
              oneWay: ['p-3'],
              twoWay: ['p-2'],
            },
            reactRouter: false,
            reduxConnect: false,
            thirdParty: false,
            // [[Prototype]]: Object,
          },
        ],
        count: 1,
        depth: 0,
        error: "",
        expanded: false,
        fileName: "Child One",
        filePath:
          "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/components/Sidebar.tsx",
        id: "FA6sF8JbqMloijRT6QOxHh3i5p1v29bJ",
        importPath: "/",
        name: "Child One",
        parentList: [
          "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/index.tsx",
        ],
        props: {
          oneWay: ['p-1'],
          twoWay: ['p-2'],
        },
        reactRouter: false,
        reduxConnect: false,
        thirdParty: false,
        // [[Prototype]]: Object,
      },
      {
        children: [{
          children: [],
          count: 1,
          depth: 0,
          error: "",
          expanded: false,
          fileName: "GrandBaby One-C",
          filePath:
            "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/components/Sidebar.tsx",
          id: "FA6sF8JbqMloijRT6QOxHh3i5p1v29bJ",
          importPath: "/",
          name: "GrandBaby One-C",
          parentList: [
            "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/index.tsx",
          ],
          props: {
            oneWay: [],
            twoWay: [],
          },
          reactRouter: false,
          reduxConnect: false,
          thirdParty: false,
          // [[Prototype]]: Object,
        },
        {
          children: [
            {
              children: [],
              count: 1,
              depth: 0,
              error: "",
              expanded: false,
              fileName: "G-G-Baby 2",
              filePath:
                "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/components/Sidebar.tsx",
              id: "FA6sF8JbqMloijRT6QOxHh3i5p1v29bJ",
              importPath: "/",
              name: "G-G-Baby 2",
              parentList: [
                "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/index.tsx",
              ],
              props: {
                oneWay: ['p-3', 'p-4', 'p-5', 'p-6'],
                twoWay: [],
              },
              reactRouter: false,
              reduxConnect: false,
              thirdParty: false,
              // [[Prototype]]: Object,
            },
          ],
          count: 1,
          depth: 0,
          error: "",
          expanded: false,
          fileName: "GrandBaby One-D",
          filePath:
            "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/components/Sidebar.tsx",
          id: "FA6sF8JbqMloijRT6QOxHh3i5p1v29bJ",
          importPath: "/",
          name: "GrandBaby One-D",
          parentList: [
            "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/index.tsx",
          ],
          props: {
            oneWay: ['p-3'],
            twoWay: ['p-2'],
          },
          reactRouter: false,
          reduxConnect: false,
          thirdParty: false,
          // [[Prototype]]: Object,
        },
      ],
        count: 1,
        depth: 0,
        error: "",
        expanded: false,
        fileName: "Child Two",
        filePath:
          "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/components/Sidebar.tsx",
        id: "FA6sF8JbqMloijRT6QOxHh3i5p1v29bJ",
        importPath: "/",
        name: "Child Two",
        parentList: [
          "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/index.tsx",
        ],
        props: {
          oneWay: [],
          twoWay: ['p-4'],
        },
        reactRouter: false,
        reduxConnect: false,
        thirdParty: false,
        // [[Prototype]]: Object,
      },
    ],
    count: 1,
    depth: 0,
    error: "",
    expanded: false,
    fileName: "Parent",
    filePath:
      "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/index.tsx",
    id: "twJWgoTMrb7UkXQI8tC1iGPX9VpfK50I",
    importPath: "/",
    name: "Parent",
    parentList: [],
    props: {
      oneWay: [],
      twoWay: [],
    },
    reactRouter: false,
    reduxConnect: false,
    thirdParty: false,
    // [[Prototype]]: Object,
  }],
  count: 1,
  depth: 0,
  error: "",
  expanded: false,
  fileName: "Index.tsx",
  filePath:
    "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/components/Sidebar.tsx",
  id: "FA6sF8JbqMloijRT6QOxHh3i5p1v29bJ",
  importPath: "/",
  name: "Index.tsx",
  parentList: [
    "/Users/abehenderson/Documents/Codesmith/ReacTree/src/webview/index.tsx",
  ],
  props: {
    oneWay: [],
    twoWay: [],
  },
  reactRouter: false,
  reduxConnect: false,
  thirdParty: false,
  // [[Prototype]]: Object,
};

       

